{
 "title": "DWH",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Last run status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dwh_dag_status", "legendFormat": "{{dag}}" }
   ]
  },
  {
   "title": "Active DAGs",
   "type": "stat",
   "gridPos": { "h": 17, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dwh_dag_enabled", "legendFormat": "{{dag}}" }
   ]
  },
  {
   "title": "Dag duration",
   "type": "stat",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dwh_dag_duration_seconds", "legendFormat": "{{dag}}" }
   ]
  }
 ]
}