apiVersion: 1

# List of datasources to insert/update depending on what's available in Grafana
# This file will be mounted into the container and picked up by Grafana on startup

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: true
